### ISSUE TITLE
Securing jx cluster

### ISSUE THREAD

**Issue by hrvolapeter** [jenkins-x/terraform-google-jx#139]
Issue for https://github.com/jenkins-x/terraform-google-jx/pull/138

My concern when using the current versions of jx is security. Cluster master and nodes are publicly exposed which simplifies set-up but increases attack surface. I created a proposal to refactoring terraform module for GCP.

The main change is to allow users to create fully private cluster hosting Jenkins (example here). However, this required some refactoring for structure of the project.

Having private cluster requires first having proxy to access the master which may require some custom scripts. In the PR I've split the existing terraform modules to two stages:

Platform setup - creates GKE infrastructure supporting jx
Application setup - creates Kubernetes resources (namespaces, k8s service account)
This PR keeps top-level main module which should still allow simple set-up while more advanced users can take advantages of different stages to do some custom work in between. This is just a proposal and will probably need some discussion. Let me know what you think

**Comment by hrvolapeter** [comment]
@ankitm123:
> Would be good to create an issue around it. PRs are not for discussions of proposals.
> 
> I am a bit confused, this can't be done in the current structure?
> From a security perspective, I would suggest adding static analysis of the terraform code using tfsec (we have this in eks module, with some exceptions) and then a compliance testing using teraform-compliance.
> 
> For example, in eks, you can use private subnet for your worker nodes, and then use nat gateway for them to access things in the dmz. Using security groups and nacl you can virtually lock down your infrastructure. I am not sure abt the equivalent in the gcp world.

In the current set-up it isn't possible to have fully private cluster. I checked also EKS repo and it seems you also cannot have private master. Once you create a private master then you get into trouble of actually connecting to it. In this case GCP allows to have bastion host on private network and use identity aware proxy (IAP) to connect to private network and communicate with GKE. As you mentioned Security groups (firewall rules) can limit access to specific ports and ip addresses but [Beyondcorp model](https://www.beyondcorp.com) discourages use of network based security and instead recommends to use solutions as IAP where the access is granted based on the identity.

As for the tfsec I think that would be the next step after we're able to create private clusters. As tfsec is mostly concerned with misconfiguration rather than the overall design.

**Comment by ankitm123** [comment]
> In the current set-up it isn't possible to have fully private cluster. I checked also EKS repo and it seems you also cannot have private master. Once you create a private master then you get into trouble of actually connecting to it. In this case GCP allows to have bastion host on private network and use identity aware proxy (IAP) to connect to private network and communicate with GKE. As you mentioned Security groups (firewall rules) can limit access to specific ports and ip addresses but [Beyondcorp model](https://www.beyondcorp.com) discourages use of network based security and instead recommends to use solutions as IAP where the access is granted based on the identity.

Isn't it this? https://docs.aws.amazon.com/eks/latest/userguide/cluster-endpoint.html. If yes, it's a flag in the module we use internally for the jx module (not exposed, but would be happy to expose it, it's good for security, I like ur idea)
As for IAP -> ur talking about IAM?
I think it might be an issue in the gcp structure, but may be not for eks -> I will take a look. Specifically how to connect to master with private endpoint. 

Very nice points :100:  

I will use this issue as a template to work on the eks one.

**Comment by hrvolapeter** [comment]
[IAP](https://cloud.google.com/iap) is different from IAM but it uses IAM for permissions. IAP is implementation of zero-trust model, it allows GPC customers to authenticate against google services using their google identities. User are authenticated at the HTTP load balancer and identity is included in the upstream request headers. Among other things IAP can be used for out-of-band access for private networks (in this case IAM verifies that user can access ssh on a server in a particular private network)

**Comment by hrvolapeter** [comment]
@jstrachan would you have some time to provide your input on this proposal?
