### ISSUE TITLE
Creating new GKE cluster throws `Error: Unsupported argument` due to "load_config_file" in provider "kubernetes" 

### ISSUE THREAD

**Issue by haysclark** [jenkins-x/terraform-google-jx#173]
When creating a new GCP cluster for JX v3 I encounter the following error:

```
Error: Unsupported argument

  on .terraform/modules/jx/main.tf line 44, in provider "kubernetes":
  44:   load_config_file = false

An argument named "load_config_file" is not expected here.
```

My version of terraform:

```
terraform -v
Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/google v3.53.0
+ provider registry.terraform.io/hashicorp/google-beta v3.53.0
+ provider registry.terraform.io/hashicorp/helm v1.3.2
+ provider registry.terraform.io/hashicorp/kubernetes v2.0.0
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/random v3.0.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

Snipped from `.terraform.lock.hcl'
```
provider "registry.terraform.io/hashicorp/kubernetes" {
  version     = "2.0.0"
  constraints = ">= 1.11.0"
}
```

**Comment by haysclark** [comment]
AKS users ran into similar issue mentioned in [this slack tread](https://kubernetes.slack.com/archives/C9MBGQJRH/p1608737372064800); however, in that repo they opted to [delete the line](https://github.com/jx3-gitops-repositories/jx3-terraform-azure/commit/09a89648e327b5063dce3b13ad5599af5517f244) of `main.tf` containing "load_config_file"... maybe they should have opted for a version strategy?

In this repo, it looks like the issue could be resolved by simply changing a `>=` with `~>` for the "kubernetes" provider.

e.g.
```
provider "kubernetes" {
  version          = "~> 1.11.0"
```

**Comment by cagiti** [comment]
@haysclark I'd say there are 2 steps required. Limit the version constraint as you've stated in order to resolve the blocking issue. Then upgrade to use the latest major (v2.0.0) version of the `kubernetes` provider and a new major release of the `terraform-google-jx` module.
