### ISSUE TITLE
Error when loading "Kubernetes" provider details for Jenkinsx cluster creation and  Terraform apply failing

### ISSUE THREAD

**Issue by AnjuMeleth** [jenkins-x/terraform-google-jx#177]
Error when loading "Kubernetes" provider details for Jenkinsx cluster creation and  Terraform apply failing. Steps below:

root@developer1:~/jenkinsx-setup-demo# terraform apply

Error: Unsupported argument

  on .terraform/modules/jx/main.tf line 44, in provider "kubernetes":
  44:   load_config_file = false

An argument named "load_config_file" is not expected here.

**How I resolved?**
By removing the line "load_config_file = false" in .terraform/modules/jx/main.tf solved the problem.

**Comment by msvticket** [comment]
This is fixed
