### ISSUE TITLE
Support for Terraform 1.x

### ISSUE THREAD

**Issue by Pokom** [jenkins-x/terraform-google-jx#204]
When initializing a project with terraform `1.0.2`, `terraform init` fails due to constraints for the provider. I've forked the repo bumped the constraint to 1.0.2 and was able to spin up a new project. I can provide logs for the warnings later in the day.

Is the team open to me submitting a PR to bump the version? I looked over the CONTRIBUTING file, and was curious to see what other ways I can test other then running an apply and making sure it works.

**Comment by ankitm123** [comment]
/close
This is already fixed.
