### ISSUE TITLE
Add support for Azure

### ISSUE THREAD

**Issue by sharepointoscar** [jenkins-x/terraform-google-jx#30]
Would it make sense to also support Azure?  Looks like it would be based on community feedback  https://github.com/jenkins-x/jx/issues/6780#issuecomment-590105921

/cc @daveconde

**Comment by hferentschik** [comment]
It does, but that will come in a different repository, something like terraform-azure-jx. 
That's how Terraform modules work. See also https://www.terraform.io/docs/registry/modules/publish.html.
