### ISSUE TITLE
Use Terraform variable validation for checking TLS email

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/terraform-google-jx#43]
The _tls_email_ variable needs to be conditionally set if custom domains are enabled. Right now when you set _parent_domain_ there is no validation which ensures that you also set _tls_email_. Missing to set this variable will read to issues later during `jx boot`.

Using Terraforms variable validation - https://www.terraform.io/docs/configuration/variables.html - this conditional dependency could be expressed. On the downside, variable validation is atm still an experimental feature.

**Comment by ankitm123** [comment]
This is now GA in 0.13.
