### ISSUE TITLE
Include disabled ingress section for jx-requirements.yaml

### ISSUE THREAD

**Issue by deanesmith** [jenkins-x/terraform-google-jx#50]
Even if a `parent_domain` parameter is not specified in a main.tf file, include a disabled ingress section in the `jx-requirements.yaml` output.  This will better allow for the subsequent ability to supply DNS and/or TLS values prior to running `jx boot`

**Comment by JPS40** [comment]
So Dean did you Mal enjoy downloading my information of my laptop while I trying to fuck her? Y’all sad as fuck good luck on my way to press charges
