### ISSUE TITLE
Make the cluster regional

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/terraform-google-jx#78]
The `zone` field should be changed to `location`. Depending on the value, GKE will be zonal (e.g., `us-east1-b`) or regional (`us-east1`).

Make sure to update the docs to clarify that the initial number of nodes is multiplied by the number of zones. If, for example, a cluster is regional, `1` node size would result in `3` nodes (one in each of the three zones).

**Comment by hferentschik** [comment]
Relates to issue #66
