### ISSUE TITLE
Terraform plan

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/terraform-google-jx#79]
When I execute `terraform plan`, there are 54 resources to be created. Are all those mandatory? Also, what are they used for? If `terraform plan` is also used as "executable specification of requirements", we need to know what is each of those resources used for, so that we know what to create depending on the choices of the components we want to use with JX.

**Comment by hferentschik** [comment]
> When I execute terraform plan, there are 54 resources to be created. Are all those mandatory?

The short answer is no. Also, the number of Terraform resources is really not 1:1 convertible to the high-level requirements in terms of Jenkins X. Terraform counts the creation of the `jx-requirements.yml` as a resource. As does it count the creation of the intermediate helper resources like _random_id.random_. Also to set up workload identity for a given Kubernetes Service Account you need multiple resources. For example, for the Velero setup, you need the Kubernetes Service Account, the Google Cloud Service account, the permissions for the Google Cloud service account, the mapping between the Kubernetes Service Account and the Google Cloud service account ...

So Terraform does need to create all these resources to achieve the setup we are after, in particular with workload identity. When it comes down to it and one also leaves the setup of permissions to the user, then all we need is a set of buckets and service accounts. See also https://github.com/jenkins-x/terraform-azurerm-jx/issues/1.

Technically, the Terraform plan describes the full setup, but I don't think we get around describing the required resources on a different abstraction level as well.

@vfarcic  - Does that help?
