### ISSUE TITLE
Unable to delete storage bucket during 'terraform destroy'

### ISSUE THREAD

**Issue by vfarcic** [jenkins-x/terraform-google-jx#80]
When trying to execute `terraform destroy`, the following error message pops up.

```
Error: Error reading Storage Bucket "backup-jx-demo-4cabfed7eb9f": googleapi: Error 403: viktor@farcic.com does not have storage.buckets.get access to backup-jx-demo-4cabfed7eb9f., forbidden
```

**Comment by vfarcic** [comment]
<img width="1003" alt="Screenshot 2020-04-30 at 16 23 37" src="https://user-images.githubusercontent.com/5716227/80721845-00076680-8aff-11ea-9028-1c3e9c9d1333.png">

**Comment by hferentschik** [comment]
My guess is that you as local gcloud user _viktor@farcic.com_ don't have storage permissions or at least not sufficient. Terraform will run with your locally authenticated user, so we would need to check the permissions for this user.

I guess that a `gcloud auth list` shows  _viktor@farcic.com_ as currently logged in user.
The bucket itself should show permissions for the velero service account:

```
gsutil iam get gs://backup-jx-demo-4cabfed7eb9f
{
  "bindings": [
    {
      "members": [
        "serviceAccount:jx-demo-vo@***.iam.gserviceaccount.com"
      ],
      "role": "roles/storage.admin"
    },
    {
      "members": [
        "serviceAccount:jx-demo-vo@***.iam.gserviceaccount.com"
      ],
      "role": "roles/storage.objectAdmin"
    },
    {
      "members": [
        "serviceAccount:jx-demo-vo@***.iam.gserviceaccount.com"
      ],
      "role": "roles/storage.objectCreator"
    }
  ],
  "etag": "CAI="
}
```

**Comment by hferentschik** [comment]
Next question, can you re-produce this? ;-)

**Comment by vfarcic** [comment]
I managed to reproduce is and now I can say that the issue is related to `jx boot`.

After `terraform apply`, a bucket with "normal" permissions is created. However, after running `jx boot`, the permissions of that bucket are changed.

Please take a look at the screenshots and focus on the bucket that ends with `468`. The first one was taken after `terraform apply` while the second was taken after `jx boot`. 

<img width="1016" alt="Screenshot 2020-05-07 at 15 34 26" src="https://user-images.githubusercontent.com/5716227/81309322-1c694d00-9083-11ea-84a1-c675389df127.png">

<img width="1019" alt="Screenshot 2020-05-07 at 16 50 11" src="https://user-images.githubusercontent.com/5716227/81309382-2b4fff80-9083-11ea-8a35-0eef65d0b4e1.png">

The rest of the buckets are OK, and only the backup ends up with "strange" permissions (during `jx boot`) that prevents me with full admin rights to remove it.

**Comment by vfarcic** [comment]
Do you have any news about this one @hferentschik ?

**Comment by hferentschik** [comment]
> Do you have any news about this one @hferentschik ?

I think it is Velero itself which changes permissions here. I am planning to take a closer look asap.

**Comment by vfarcic** [comment]
I have it confirmed that it's not only me. At least one person from the workshop that just finished experienced the same issue.

**Comment by ifosch** [comment]
I got into the same issue during the Cloudbees Connect Intro to Jenkins X workshop, so I got my GCP account created from scratch, as well as my credentials.
I got this error message:
```
Error: Error reading Storage Bucket "backup-tf-jx-primary-caiman-3d32c81d0664": googleapi: Error 403: terraform-test@dark-blade-277811.iam.gserviceaccount.com does not have storage.buckets.get access to the Google Cloud Storage bucket., forbidden
```
I also can't see the details of the bucket from GCP console. I cannot even remove it manually from the Console.

**Comment by mtreeman** [comment]
I had the same issue here setting up gke on macOS with Terraform 
`Error: Error reading Storage Bucket "backup-tf-jx-emerging-quail-95d4aad80574": googleapi: Error 403: mark@mail.de does not have storage.buckets.get access to the Google Cloud Storage bucket., forbidden`

**Comment by hferentschik** [comment]
I am still not able to reproduce this. I can successfully destroy a cluster with `terraform destroy` even if there are existing backups in the bucket. 

@vfarcic, are you making use of the `force_destroy` variable?

**Comment by vfarcic** [comment]
`force_destroy` does not change the situation. It cannot be destroyed no matter the method.

**Comment by hferentschik** [comment]
@vfarcic, could you try something else which may help to narrow down the problem. Run `terraform apply` and then edit the generated `jx-requirements.yml` before running `jx boot`, deleting the _velero_ configuration altogether. This way the actual bucket is created together with the service account etc, but Velero itself does not get installed (see https://github.com/jenkins-x/jenkins-x-boot-config/blob/master/systems/velero/values.tmpl.yaml and https://github.com/jenkins-x/jenkins-x-boot-config/blob/master/systems/velero-backups/values.tmpl.yaml).

**Comment by hferentschik** [comment]
@vfarcic - another thought, you could check the storage audit logs and see whether you can see something there. If the audit logs are turned on, you should be able to see when the permission change.

Might be worth upgrading the Velero chart we are using as well. It's 1.0.0, but there is a 1.1.0 available assuming the error lies on the Velero side).

**Comment by vfarcic** [comment]
I deleted the whole project in GCP as a way to remove those storages.

It should be relatively easy to reproduce the issue since others are hitting it as well. I can create a new project and `terraform apply` the module if you'd like me to share my screen if that's would help debug.

**Comment by tgelpi-gmail** [comment]
I had the same problem removing the bucket when using Terraform with Velero enabled.  I was able to preserve my project and remove the buckets with my owner id by first removing the service accounts policy bindings and service accounts.

<p>
gcloud iam service-acccounts list<br>
gcloud projects get-iam-policy ${PROJECT}<br>
<br>
 Below are entries for Velero bucket<br>
<br>
gcloud projects remove-iam-policy-binding ${PROJECT} \<br>
&nbsp;&nbsp;&nbsp;--member  serviceAccount:${CLUSTER}-vo@${PROJECT}.iam.gserviceaccount.com --role roles/storage.admin<br>
gcloud projects remove-iam-policy-binding ${PROJECT} \<br>
&nbsp;&nbsp;&nbsp;--member  serviceAccount:${CLUSTER}-vo@${PROJECT}.iam.gserviceaccount.com --role roles/storage.objectAdmin<br>
gcloud projects remove-iam-policy-binding ${PROJECT} \<br>
&nbsp;&nbsp;&nbsp;--member  serviceAccount:${CLUSTER}-vo@${PROJECT}.iam.gserviceaccount.com --role roles/storage.objectCreator<br>
gcloud iam service-accounts delete ${CLUSTER}-vo@${PROJECT}.iam.gserviceaccount.com --quiet<br>
</p>
