### ISSUE TITLE
Creating namespaces seems like scope creep for this module

### ISSUE THREAD

**Issue by cagiti** [jenkins-x/terraform-google-jx#82]
```terraform
resource "kubernetes_namespace" "cert-manager" {
  metadata {
    name = var.cert-manager-namespace
  }
  lifecycle {
    ignore_changes = [
      metadata[0].labels,
      metadata[0].annotations,
    ]
  }
}
```

This module creates namespaces (jx, cert-manager, velero), which seems to be outside the scope of this modules intent. From past experiences it becomes difficult when mixing resource creation where resources have differing lifecycles and where more than one agent is responsible for configuring said resources (can cause conflicts).

**Comment by hferentschik** [comment]
Agreed, eventually, we should not create the namespaces at all. Initially, the namespace creation was conditional but got changed as part of issue #72.

If you create a cluster w/o DNS (using nip.io) and then run `jx boot`, Boot will create the namespaces. If you then want to use DNS, set the domain in the Terraform script and run `terraform apply` it will fail, since the namespace already is created and not managed by Terraform. 

One could try to make some changes to boot as well so that these namespaces can be conditionally created. Alternatively, one could take the stance that these settings are not changeable. So you need to decide on w/ or w/o domain upfront. Then it becomes a bit of a user experience/documentation issue. 

Not sure what the best solution is tbh. WDYT?

**Comment by cagiti** [comment]
> Agreed, eventually, we should not create the namespaces at all. Initially, the namespace creation was conditional but got changed as part of issue #72.
> 
> If you create a cluster w/o DNS (using nip.io) and then run `jx boot`, Boot will create the namespaces. If you then want to use DNS, set the domain in the Terraform script and run `terraform apply` it will fail, since the namespace already is created and not managed by Terraform.
> 
> One could try to make some changes to boot as well so that these namespaces can be conditionally created. Alternatively, one could take the stance that these settings are not changeable. So you need to decide on w/ or w/o domain upfront. Then it becomes a bit of a user experience/documentation issue.
> 
> Not sure what the best solution is tbh. WDYT?

Thanks for the reply... I'll have a think on this scenario 👍

**Comment by cagiti** [comment]
> If you create a cluster w/o DNS (using nip.io) and then run `jx boot`, Boot will create the namespaces. If you then want to use DNS, set the domain in the Terraform script and run `terraform apply` it will fail, since the namespace already is created and not managed by Terraform.

How does terraform fail in the scenario described? If terraform was attempting to create the cert-manager namespace then it make sense, but this issue was created to remove any resource creation within the cluster as that should be the responsibility of `jx boot`.

**Comment by cagiti** [comment]
We should remove the use of the kubernetes provider completely from this module and avoid creating any resources within the cluster. There should be a complete separation between what terraform manages and what Jenkins X manages, having terraform manage resources created within the cluster will cause terraform and Jenkins X to fight against one another.

**Comment by patrickleet** [comment]
There's some good conversation on this here:
https://github.com/hashicorp/terraform-provider-kubernetes/issues/613#issuecomment-559473848

Could possibly do something where you can use the data source or create it if that data source doesn't exist - the details and syntax of that I have not attempted yet.

**Comment by patrickleet** [comment]
Update: tried that - didn't quite work out that way
https://github.com/jenkins-x/terraform-aws-eks-jx/pull/109#issuecomment-656705845

**Comment by chrismellard** [comment]
Further question on the topic of the line between terraform and jx boot would be how do we envisage passing secrets between the two if we do not want terraform creating Kubernetes secrets? i.e. if we're trying to hold a line on terraform creating non-k8s resources and `jx boot` creating k8s resources. An example would be creating Azure application registrations for the purpose of client credential grants required by components in the cluster, here the terraform module would ideally create the Azure app-reg resource, have a client secret it wished to pass to Velero chart somehow. Seems to me that a k8s secret created by terraform here would be a secure expedient way to achieve this but it is contra to the divide described above. How do we solve the secret transmission issue between terraform and `jx boot`?

**Comment by jstrachan** [comment]
maybe one way forward is if Terraform needs to make things, it uses its own namespace which it owns and is quite separate from Jenkins X + its namespaces?

incidentally with Jenkins X 3.x we've defaulted to not creating the `jx` namespace any more; we do that in Jenkins X and terraform just makes GCP resources
