### ISSUE TITLE
local terraform provider version scope too narrow

### ISSUE THREAD

**Issue by cagiti** [jenkins-x/terraform-google-jx#84]
We've experienced an issue within our repository where we use a newer `1.4.0` version of the `local` terraform provider. Due to changes in the minor version bumps the current constraint of `~> 1.2.0` of the `local` provider corrupts our terraform state by adding `content_base64 = null`, resulting in the following [error](https://github.com/hashicorp/terraform/issues/22017):

```terraform
Error: unsupported attribute "content_base64"
```

Going forward I think all provider scopes in this module need to have their version constraints relaxed (_whilst retaining the minimum version constraint_), thus allowing the consuming project to determine which version to use.
https://www.terraform.io/docs/configuration/modules.html#provider-version-constraints-in-modules

**Comment by hferentschik** [comment]
> Due to changes in the minor version bumps the current constraint of ~> 1.2.0 of the local provider corrupts our terraform state by adding content_base64 = null

That sounds bad. I would have hoped Terraform would handle that better.
