### ISSUE TITLE
Provider version scope too narrow for module

### ISSUE THREAD

**Issue by cagiti** [jenkins-x/terraform-google-jx#88]
As per https://www.terraform.io/docs/configuration/modules.html#provider-version-constraints-in-modules

**Comment by hferentschik** [comment]
For reference:

> Shared modules should constrain only the minimum allowed version, using a >= constraint. This specifies the minimum version the provider is compatible with while allowing users to upgrade to newer provider versions without altering the module source code.

Thanks @cagiti, we got wrong for sure.
