### ISSUE TITLE
Make creation of Velero resources optional

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/terraform-google-jx#97]
ATM, the backup configuration (backup storage bucket, namespace, service account, etc) are always created. Given that this is not fully tested/supported yet, it makes sense to only create resources conditionally. One needs to explicitly opt in.

On the downside, it means that if you at a later stage want to enable it, you can create the missing resources by enabling the feature and re-running `terraform apply`, but then you will have to manually sync the required `jx-requirements.yml` changes into the `jx-requirements.yml` of your dev repository.

**Comment by hferentschik** [comment]
@vfarcic @cagiti - thoughts?

**Comment by vfarcic** [comment]
I believe that the default setup should be something that is well tested and (almost) always works. Everything that is experimental (not fully tested), that does not have a clear purpose, that is not documented, etc... should be optional.

That was high-level opinion. If we switch to Velero, I do not think the current usage of it brings sufficient value. It could be just as easily be installed without JX, and it creates potential problems if used always and by default. I would suggest adding a variable to Terraform that would not install it by default. Something like `velero = false`...
